#!/bin/bash
# properties = {"type": "single", "rule": "fastqc", "local": false, "input": ["../reads/BE3-1_combined_R1.fastq.gz", "../reads/BE3-2_combined_R1.fastq.gz", "../reads/BE4-1_combined_R1.fastq.gz", "../reads/BE4-2_combined_R1.fastq.gz", "../reads/EM-1_combined_R1.fastq.gz", "../reads/EM-2_combined_R1.fastq.gz", "../reads/BE3-1_combined_R2.fastq.gz", "../reads/BE3-2_combined_R2.fastq.gz", "../reads/BE4-1_combined_R2.fastq.gz", "../reads/BE4-2_combined_R2.fastq.gz", "../reads/EM-1_combined_R2.fastq.gz", "../reads/EM-2_combined_R2.fastq.gz"], "output": ["../qc/fastqc/BE3-1_combined_R1_fastqc.html", "../qc/fastqc/BE3-2_combined_R1_fastqc.html", "../qc/fastqc/BE4-1_combined_R1_fastqc.html", "../qc/fastqc/BE4-2_combined_R1_fastqc.html", "../qc/fastqc/EM-1_combined_R1_fastqc.html", "../qc/fastqc/EM-2_combined_R1_fastqc.html", "../qc/fastqc/BE3-1_combined_R2_fastqc.html", "../qc/fastqc/BE3-2_combined_R2_fastqc.html", "../qc/fastqc/BE4-1_combined_R2_fastqc.html", "../qc/fastqc/BE4-2_combined_R2_fastqc.html", "../qc/fastqc/EM-1_combined_R2_fastqc.html", "../qc/fastqc/EM-2_combined_R2_fastqc.html"], "wildcards": {}, "params": {"threads": "24"}, "log": ["../qc/fastqc.log"], "threads": 1, "resources": {}, "jobid": 2, "cluster": {}}
cd /gpfs/user/zhaohuanan/3.project/3.2020-05_BE3andBE4_RNA-seq/snakepipes_fastqc-multiqc && \
/home/zhaohuanan/zhaohn_HD/1.apps/anaconda3/envs/py37/bin/python3.7 \
-m snakemake ../qc/fastqc/BE3-1_combined_R1_fastqc.html --snakefile /gpfs/user/zhaohuanan/3.project/3.2020-05_BE3andBE4_RNA-seq/snakepipes_fastqc-multiqc/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /gpfs/user/zhaohuanan/3.project/3.2020-05_BE3andBE4_RNA-seq/snakepipes_fastqc-multiqc/.snakemake/tmp.urpwuusg ../reads/BE3-1_combined_R1.fastq.gz ../reads/BE3-2_combined_R1.fastq.gz ../reads/BE4-1_combined_R1.fastq.gz ../reads/BE4-2_combined_R1.fastq.gz ../reads/EM-1_combined_R1.fastq.gz ../reads/EM-2_combined_R1.fastq.gz ../reads/BE3-1_combined_R2.fastq.gz ../reads/BE3-2_combined_R2.fastq.gz ../reads/BE4-1_combined_R2.fastq.gz ../reads/BE4-2_combined_R2.fastq.gz ../reads/EM-1_combined_R2.fastq.gz ../reads/EM-2_combined_R2.fastq.gz --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
  -p --allowed-rules fastqc --nocolor --notemp --no-hooks --nolock \
--mode 2  && exit 0 || exit 1

